 const rental = [
  {
      id: 1,
      name: "Risland Sky Mansion",
      description: "Luxurious apartment with breathtaking views",
      detailedDescription: "The Risland Sky Mansion is an epitome of luxury living, offering a magnificent panoramic view of the city skyline. This spacious penthouse spans over 4,000 square feet and features state-of-the-art amenities, including a private elevator, a gourmet kitchen with high-end appliances, and a lavish master suite with a spa-like bathroom. Residents have exclusive access to a rooftop pool, a fully equipped fitness center, and a 24/7 concierge service. The Sky Mansion is designed for those who seek the ultimate in sophistication and comfort, with floor-to-ceiling windows that flood the space with natural light and provide breathtaking views from every room.",
      price: "$1,000,000",
      image: "images/recently/image1.jpg",
      ownerName: "John Doe",
      ownerProfileLink: "https://example.com/johndoe",
      ownerProfilePhoto: "images/owners/johndoe.jpg",
      rating: 4.8,
      datePosted: "2024-06-15",
      impressions: 1200
  },
  {
      id: 2,
      name: "Seaside Villa",
      description: "Beautiful villa with private beach access",
      detailedDescription: "The Seaside Villa is a stunning property located directly on the coastline, offering unparalleled ocean views and private beach access. This beautiful villa spans over 5,000 square feet and includes five spacious bedrooms, each with an en-suite bathroom. The open-plan living area is perfect for entertaining, featuring a modern kitchen with top-of-the-line appliances, a large dining area, and a comfortable lounge that opens onto a terrace overlooking the sea. The villa also boasts a private infinity pool, a lush garden, and multiple outdoor seating areas where you can enjoy the serene surroundings. Perfect for those who love the beach and luxury living, this villa is a dream come true.",
      price: "$1,500,000",
      image: "images/recently/image2.jpg",
      ownerName: "Emily Smith",
      ownerProfileLink: "https://example.com/emilysmith",
      ownerProfilePhoto: "images/owners/emilysmith.jpg",
      rating: 4.5,
      datePosted: "2024-06-14",
      impressions: 950
  },
  {
      id: 3,
      name: "Mountain Retreat",
      description: "Cozy cabin in the mountains with stunning views",
      detailedDescription: "The Mountain Retreat is a cozy cabin nestled in the picturesque mountains, offering stunning views and a peaceful environment. This charming cabin features three bedrooms, two bathrooms, and an open-plan living area with a stone fireplace. The rustic yet modern design includes a fully equipped kitchen, a dining area with large windows, and a comfortable lounge that opens onto a spacious deck. The deck is perfect for relaxing and taking in the breathtaking mountain scenery. Additional amenities include a hot tub, a fire pit, and access to hiking trails. Ideal for nature lovers and those looking for a tranquil escape, the Mountain Retreat is the perfect getaway.",
      price: "$500,000",
      image: "images/recently/image3.jpg",
      ownerName: "William Brown",
      ownerProfileLink: "https://example.com/williambrown",
      ownerProfilePhoto: "images/owners/williambrown.jpg",
      rating: 4.7,
      datePosted: "2024-06-13",
      impressions: 1100
  },
  {
      id: 4,
      name: "City Center Loft",
      description: "Modern loft in the heart of the city",
      detailedDescription: "The City Center Loft is a modern, stylish property located in the heart of the city. This spacious loft spans over 2,500 square feet and features an open-plan design with high ceilings and large windows that provide plenty of natural light. The loft includes two bedrooms, two bathrooms, a fully equipped kitchen with stainless steel appliances, and a large living area that is perfect for entertaining. The master suite has a walk-in closet and a luxurious bathroom with a soaking tub and a separate shower. The loft also includes a private balcony with city views, a dedicated parking space, and access to a rooftop terrace. Ideal for urban professionals and those who enjoy city living, the City Center Loft offers convenience and style.",
      price: "$800,000",
      image: "images/recently/image4.jpg",
      ownerName: "Sophia Davis",
      ownerProfileLink: "https://example.com/sophiadavis",
      ownerProfilePhoto: "images/owners/sophiadavis.jpg",
      rating: 4.6,
      datePosted: "2024-06-12",
      impressions: 1300
  },
  {
      id: 5,
      name: "Lakefront Property",
      description: "Charming cottage with lake access",
      detailedDescription: "The Lakefront Property is a charming cottage located on the shores of a beautiful lake. This cozy cottage features three bedrooms, two bathrooms, and a spacious living area with a fireplace. The kitchen is fully equipped with modern appliances, and the dining area has large windows that offer stunning lake views. The cottage also includes a large deck that overlooks the lake, perfect for outdoor dining and relaxation. Additional amenities include a private dock, a boat house, and access to various water activities such as fishing, boating, and swimming. Surrounded by nature, the Lakefront Property is ideal for those seeking a peaceful and scenic retreat.",
      price: "$700,000",
      image: "images/recently/image5.jpg",
      ownerName: "James Wilson",
      ownerProfileLink: "https://example.com/jameswilson",
      ownerProfilePhoto: "images/owners/jameswilson.jpg",
      rating: 4.4,
      datePosted: "2024-06-11",
      impressions: 900
  },
  {
      id: 6,
      name: "Country Estate",
      description: "Spacious estate with sprawling grounds",
      detailedDescription: "The Country Estate is a luxurious property situated on sprawling grounds in the countryside. This grand estate features seven bedrooms, six bathrooms, and over 10,000 square feet of living space. The interior boasts elegant design elements, including a grand foyer, formal living and dining rooms, a gourmet kitchen with top-of-the-line appliances, and a spacious family room. The master suite includes a private sitting area, a large walk-in closet, and a luxurious bathroom with a soaking tub and a separate shower. The estate also includes a guest house, a swimming pool, a tennis court, and beautifully landscaped gardens. Perfect for those seeking privacy and luxury, the Country Estate is a true gem.",
      price: "$2,000,000",
      image: "images/recently/image6.jpg",
      ownerName: "Linda Martinez",
      ownerProfileLink: "https://example.com/lindamartinez",
      ownerProfilePhoto: "images/owners/lindamartinez.jpg",
      rating: 4.9,
      datePosted: "2024-06-10",
      impressions: 1400
  },
  {
      id: 7,
      name: "Urban Penthouse",
      description: "Luxurious penthouse in the heart of the city",
      detailedDescription: "The Urban Penthouse is a stunning property located in the heart of the city, offering luxurious living spaces and breathtaking views. This expansive penthouse spans over 6,000 square feet and includes four bedrooms, five bathrooms, and an open-plan living area with floor-to-ceiling windows. The modern kitchen is equipped with high-end appliances, and the living and dining areas are perfect for entertaining. The master suite features a private balcony, a walk-in closet, and a spa-like bathroom. The penthouse also includes a private rooftop terrace with a hot tub, outdoor kitchen, and lounge areas. Residents have access to exclusive amenities, including a fitness center, a swimming pool, and a 24/7 concierge service. Ideal for those seeking luxury and convenience, the Urban Penthouse is the ultimate urban retreat.",
      price: "$3,000,000",
      image: "images/recently/image7.jpg",
      ownerName: "David Lee",
      ownerProfileLink: "https://example.com/davidlee",
      ownerProfilePhoto: "images/owners/davidlee.jpg",
      rating: 4.8,
      datePosted: "2024-06-09",
      impressions: 1600
  },
  {
      id: 8,
      name: "Beachfront Condo",
      description: "Stunning condo with panoramic ocean views",
      detailedDescription: "The Beachfront Condo offers stunning panoramic ocean views and luxurious living spaces. This beautiful condo spans over 3,000 square feet and includes three bedrooms, three bathrooms, and an open-plan living area with large windows. The modern kitchen is fully equipped with high-end appliances, and the living and dining areas are perfect for entertaining. The master suite features a private balcony, a walk-in closet, and a luxurious bathroom. Additional amenities include a private pool, direct beach access, and a fitness center. Perfect for those seeking a luxurious beachfront lifestyle, this condo is a dream home.",
      price: "$1,200,000",
      image: "images/recently/image8.jpg",
      ownerName: "Michael Johnson",
      ownerProfileLink: "https://example.com/michaeljohnson",
      ownerProfilePhoto: "images/owners/michaeljohnson.jpg",
      rating: 4.7,
      datePosted: "2024-06-08",
      impressions: 1000
  },
  {
      id: 9,
      name: "Country Cottage",
      description: "Quaint cottage in a peaceful countryside setting",
      detailedDescription: "The Country Cottage is a quaint and charming property located in a peaceful countryside setting. This cozy cottage features two bedrooms, one bathroom, and a comfortable living area with a fireplace. The kitchen is fully equipped with modern appliances, and the dining area offers lovely views of the surrounding countryside. The cottage also includes a large garden with a patio area, perfect for outdoor dining and relaxation. Additional amenities include a small pond, a vegetable garden, and access to nearby walking trails. Ideal for those seeking a serene and simple lifestyle, the Country Cottage is a perfect retreat.",
      price: "$400,000",
      image: "images/recently/image9.jpg",
      ownerName: "Sarah Taylor",
      ownerProfileLink: "https://example.com/sarahtaylor",
      ownerProfilePhoto: "images/owners/sarahtaylor.jpg",
      rating: 4.3,
      datePosted: "2024-06-07",
      impressions: 800
  },
  {
      id: 10,
      name: "Garden Villa",
      description: "Elegant villa with lush garden and pool",
      detailedDescription: "The Garden Villa is an elegant property featuring a lush garden and a private pool. This beautiful villa spans over 4,500 square feet and includes four bedrooms, four bathrooms, and an open-plan living area with large windows. The modern kitchen is fully equipped with high-end appliances, and the living and dining areas are perfect for entertaining. The master suite features a private balcony, a walk-in closet, and a luxurious bathroom. The villa also includes a large terrace, a landscaped garden, and a swimming pool. Additional amenities include a home gym, a wine cellar, and a garage. Ideal for those seeking a luxurious and tranquil lifestyle, the Garden Villa is a true oasis.",
      price: "$1,800,000",
      image: "images/recently/image10.jpg",
      ownerName: "Laura Harris",
      ownerProfileLink: "https://example.com/lauraharris",
      ownerProfilePhoto: "images/owners/lauraharris.jpg",
      rating: 4.8,
      datePosted: "2024-06-06",
      impressions: 1200
  }
];

const recently = [
  {
      id: 1,
      name: "Risland Sky Mansion",
      description: "Luxurious apartment with breathtaking views",
      detailedDescription: "The Risland Sky Mansion is an epitome of luxury living, offering a magnificent panoramic view of the city skyline. This spacious penthouse spans over 4,000 square feet and features state-of-the-art amenities, including a private elevator, a gourmet kitchen with high-end appliances, and a lavish master suite with a spa-like bathroom. Residents have exclusive access to a rooftop pool, a fully equipped fitness center, and a 24/7 concierge service. The Sky Mansion is designed for those who seek the ultimate in sophistication and comfort, with floor-to-ceiling windows that flood the space with natural light and provide breathtaking views from every room.",
      price: "$1,000,000",
      image: "images/recently/image1.jpg",
      ownerName: "John Doe",
      ownerProfileLink: "https://example.com/johndoe",
      ownerProfilePhoto: "images/owners/johndoe.jpg",
      rating: 4.8,
      datePosted: "2024-06-15",
      impressions: 1200
  },
  {
      id: 2,
      name: "Seaside Villa",
      description: "Beautiful villa with private beach access",
      detailedDescription: "The Seaside Villa is a stunning property located directly on the coastline, offering unparalleled ocean views and private beach access. This beautiful villa spans over 5,000 square feet and includes five spacious bedrooms, each with an en-suite bathroom. The open-plan living area is perfect for entertaining, featuring a modern kitchen with top-of-the-line appliances, a large dining area, and a comfortable lounge that opens onto a terrace overlooking the sea. The villa also boasts a private infinity pool, a lush garden, and multiple outdoor seating areas where you can enjoy the serene surroundings. Perfect for those who love the beach and luxury living, this villa is a dream come true.",
      price: "$1,500,000",
      image: "images/recently/image2.jpg",
      ownerName: "Emily Smith",
      ownerProfileLink: "https://example.com/emilysmith",
      ownerProfilePhoto: "images/owners/emilysmith.jpg",
      rating: 4.5,
      datePosted: "2024-06-14",
      impressions: 950
  },
  {
      id: 3,
      name: "Mountain Retreat",
      description: "Cozy cabin in the mountains with stunning views",
      detailedDescription: "The Mountain Retreat is a cozy cabin nestled in the picturesque mountains, offering stunning views and a peaceful environment. This charming cabin features three bedrooms, two bathrooms, and an open-plan living area with a stone fireplace. The rustic yet modern design includes a fully equipped kitchen, a dining area with large windows, and a comfortable lounge that opens onto a spacious deck. The deck is perfect for relaxing and taking in the breathtaking mountain scenery. Additional amenities include a hot tub, a fire pit, and access to hiking trails. Ideal for nature lovers and those looking for a tranquil escape, the Mountain Retreat is the perfect getaway.",
      price: "$500,000",
      image: "images/recently/image3.jpg",
      ownerName: "William Brown",
      ownerProfileLink: "https://example.com/williambrown",
      ownerProfilePhoto: "images/owners/williambrown.jpg",
      rating: 4.7,
      datePosted: "2024-06-13",
      impressions: 1100
  },
  {
      id: 4,
      name: "City Center Loft",
      description: "Modern loft in the heart of the city",
      detailedDescription: "The City Center Loft is a modern, stylish property located in the heart of the city. This spacious loft spans over 2,500 square feet and features an open-plan design with high ceilings and large windows that provide plenty of natural light. The loft includes two bedrooms, two bathrooms, a fully equipped kitchen with stainless steel appliances, and a large living area that is perfect for entertaining. The master suite has a walk-in closet and a luxurious bathroom with a soaking tub and a separate shower. The loft also includes a private balcony with city views, a dedicated parking space, and access to a rooftop terrace. Ideal for urban professionals and those who enjoy city living, the City Center Loft offers convenience and style.",
      price: "$800,000",
      image: "images/recently/image4.jpg",
      ownerName: "Sophia Davis",
      ownerProfileLink: "https://example.com/sophiadavis",
      ownerProfilePhoto: "images/owners/sophiadavis.jpg",
      rating: 4.6,
      datePosted: "2024-06-12",
      impressions: 1300
  },
  {
      id: 5,
      name: "Lakefront Property",
      description: "Charming cottage with lake access",
      detailedDescription: "The Lakefront Property is a charming cottage located on the shores of a beautiful lake. This cozy cottage features three bedrooms, two bathrooms, and a spacious living area with a fireplace. The kitchen is fully equipped with modern appliances, and the dining area has large windows that offer stunning lake views. The cottage also includes a large deck that overlooks the lake, perfect for outdoor dining and relaxation. Additional amenities include a private dock, a boat house, and access to various water activities such as fishing, boating, and swimming. Surrounded by nature, the Lakefront Property is ideal for those seeking a peaceful and scenic retreat.",
      price: "$700,000",
      image: "images/recently/image5.jpg",
      ownerName: "James Wilson",
      ownerProfileLink: "https://example.com/jameswilson",
      ownerProfilePhoto: "images/owners/jameswilson.jpg",
      rating: 4.4,
      datePosted: "2024-06-11",
      impressions: 900
  },
  {
      id: 6,
      name: "Country Estate",
      description: "Spacious estate with sprawling grounds",
      detailedDescription: "The Country Estate is a luxurious property situated on sprawling grounds in the countryside. This grand estate features seven bedrooms, six bathrooms, and over 10,000 square feet of living space. The interior boasts elegant design elements, including a grand foyer, formal living and dining rooms, a gourmet kitchen with top-of-the-line appliances, and a spacious family room. The master suite includes a private sitting area, a large walk-in closet, and a luxurious bathroom with a soaking tub and a separate shower. The estate also includes a guest house, a swimming pool, a tennis court, and beautifully landscaped gardens. Perfect for those seeking privacy and luxury, the Country Estate is a true gem.",
      price: "$2,000,000",
      image: "images/recently/image6.jpg",
      ownerName: "Linda Martinez",
      ownerProfileLink: "https://example.com/lindamartinez",
      ownerProfilePhoto: "images/owners/lindamartinez.jpg",
      rating: 4.9,
      datePosted: "2024-06-10",
      impressions: 1400
  },
  {
      id: 7,
      name: "Urban Penthouse",
      description: "Luxurious penthouse in the heart of the city",
      detailedDescription: "The Urban Penthouse is a stunning property located in the heart of the city, offering luxurious living spaces and breathtaking views. This expansive penthouse spans over 6,000 square feet and includes four bedrooms, five bathrooms, and an open-plan living area with floor-to-ceiling windows. The modern kitchen is equipped with high-end appliances, and the living and dining areas are perfect for entertaining. The master suite features a private balcony, a walk-in closet, and a spa-like bathroom. The penthouse also includes a private rooftop terrace with a hot tub, outdoor kitchen, and lounge areas. Residents have access to exclusive amenities, including a fitness center, a swimming pool, and a 24/7 concierge service. Ideal for those seeking luxury and convenience, the Urban Penthouse is the ultimate urban retreat.",
      price: "$3,000,000",
      image: "images/recently/image7.jpg",
      ownerName: "David Lee",
      ownerProfileLink: "https://example.com/davidlee",
      ownerProfilePhoto: "images/owners/davidlee.jpg",
      rating: 4.8,
      datePosted: "2024-06-09",
      impressions: 1600
  },
  {
      id: 8,
      name: "Beachfront Condo",
      description: "Stunning condo with panoramic ocean views",
      detailedDescription: "The Beachfront Condo is a stunning property offering panoramic ocean views. This modern condo spans over 3,000 square feet and includes three bedrooms, three bathrooms, and an open-plan living area with large windows. The kitchen is fully equipped with high-end appliances, and the living and dining areas are perfect for entertaining. The master suite features a private balcony with ocean views, a walk-in closet, and a luxurious bathroom. The condo also includes a large terrace, a private pool, and access to beach amenities. Ideal for those seeking a luxurious and tranquil lifestyle by the ocean, the Beachfront Condo is a perfect choice.",
      price: "$1,200,000",
      image: "images/recently/image8.jpg",
      ownerName: "Michael Clark",
      ownerProfileLink: "https://example.com/michaelclark",
      ownerProfilePhoto: "images/owners/michaelclark.jpg",
      rating: 4.6,
      datePosted: "2024-06-08",
      impressions: 1000
  },
  {
      id: 9,
      name: "Country Cottage",
      description: "Quaint cottage in a peaceful countryside setting",
      detailedDescription: "The Country Cottage is a quaint and charming property located in a peaceful countryside setting. This cozy cottage features two bedrooms, one bathroom, and a comfortable living area with a fireplace. The kitchen is fully equipped with modern appliances, and the dining area offers lovely views of the surrounding countryside. The cottage also includes a large garden with a patio area, perfect for outdoor dining and relaxation. Additional amenities include a small pond, a vegetable garden, and access to nearby walking trails. Ideal for those seeking a serene and simple lifestyle, the Country Cottage is a perfect retreat.",
      price: "$400,000",
      image: "images/recently/image9.jpg",
      ownerName: "Sarah Taylor",
      ownerProfileLink: "https://example.com/sarahtaylor",
      ownerProfilePhoto: "images/owners/sarahtaylor.jpg",
      rating: 4.3,
      datePosted: "2024-06-07",
      impressions: 800
  },
  {
      id: 10,
      name: "Garden Villa",
      description: "Elegant villa with lush garden and pool",
      detailedDescription: "The Garden Villa is an elegant property featuring a lush garden and a private pool. This beautiful villa spans over 4,500 square feet and includes four bedrooms, four bathrooms, and an open-plan living area with large windows. The modern kitchen is fully equipped with high-end appliances, and the living and dining areas are perfect for entertaining. The master suite features a private balcony, a walk-in closet, and a luxurious bathroom. The villa also includes a large terrace, a landscaped garden, and a swimming pool. Additional amenities include a home gym, a wine cellar, and a garage. Ideal for those seeking a luxurious and tranquil lifestyle, the Garden Villa is a true oasis.",
      price: "$1,800,000",
      image: "images/recently/image10.jpg",
      ownerName: "Laura Harris",
      ownerProfileLink: "https://example.com/lauraharris",
      ownerProfilePhoto: "images/owners/lauraharris.jpg",
      rating: 4.8,
      datePosted: "2024-06-06",
      impressions: 1200
  }
];

module.exports = { recently, rental };
